ignores:
 - "@typescript-eslint/eslint-plugin"
 - "@typescript-eslint/parser"
 - eslint
 - eslint-config-airbnb-base
 - eslint-config-prettier
 - eslint-plugin-import
 - eslint-plugin-json
 - eslint-plugin-prettier
 - prettier
 - somethingJustDontExist
 - yaml
 - somethingNotExist